### ISSUE TITLE
Ursprung nicht gekennzeichnet

### ISSUE THREAD

**Issue by beabel** [frankyhub/Radiowecker#1]
Hallo, leider hast du keinen einzigen Verweis auf den Ursprung des Codes bzw Projektes.
Dies macht den Anschein, das es von dir stammt!
Jedoch ist der Original Code  / Projekt von Az-Delivery. Wäre nett wenn dies erwähnt würde.
MfG

**Comment by frankyhub** [comment]
——————————————Frank Karlheinz Fachbereichsleiter Elektronik Fablab Tölzer Straße 3a83703 Gmund am ***@***.***/55538286oberlab.deAm 17.08.2024 um 00:04 schrieb kunigunde ***@***.***>:﻿
Hallo, leider hast du keinen einzigen Verweis auf den Ursprung des Codes bzw Projektes.
Dies macht den Anschein, das es von dir stammt!
Jedoch ist der Original Code  / Projekt von Az-Delivery. Wäre nett wenn dies erwähnt würde.
MfG

**Comment by frankyhub** [comment]
Danke für den Hinweis, das mache ich natürlich.
