### ISSUE TITLE
Format .AAC

### ISSUE THREAD

**Issue by samand587** [frankyhub/Radiowecker#2]
Hi! Why there is no format support.AAC?

**Comment by frankyhub** [comment]
You need a other Library

https://docs.espressif.com/projects/esp-adf/en/latest/api-reference/codecs/aac_decoder.html#:~:text=AAC%20Decoder.%20Decode%20an%20audio%20data%20stream%20provided%20in%20AAC

and edit the stations.ino, 
example:
http://stream.antenne.de/2000er-hits/stream/aacp

**Comment by frankyhub** [comment]
close

**Comment by frankyhub** [comment]
ok
