### ISSUE TITLE
LDR's work

### ISSUE THREAD

**Issue by samand587** [frankyhub/Radiowecker#3]
0 means use LDR to control brightness. Why doesn't he want to work?

**Comment by frankyhub** [comment]
hi, I'm not at home at the moment and can't check the problem. I'll write to you when I get back. please be patient.

**Comment by samand587** [comment]
How do I set my time zone?

**Comment by samand587** [comment]
Switched to radiowecker version 3.0.5- LDR does not work

**Comment by frankyhub** [comment]
Please look at wiki:

https://github.com/frankyhub/Radiowecker/wiki

**Comment by samand587** [comment]
Hallo! Ich habe alles gemäß den Empfehlungen eingerichtet, aber der Sensor funktioniert nicht. Was kann ich sonst noch in der Skizze sehen?

**Comment by frankyhub** [comment]
Was sagt der Serielle Monitor?
Programmzeile 245
Serial.printf("ldr %i letzter %i\n",tmp,lastldr);

**Comment by samand587** [comment]
Ich habe jetzt Version 3.0.5. In Ihrer Zeile 245 steht geschrieben   Serial.printf("ldr %i letzter %i\n",tmp,lastldr);
Hafen-Monitor: ets Jul 29 2019 12:21:46
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13924
ho 0 tail 12 room 4
load:0x40080400,len:3600
entry 0x400805f0
Load preferences
station 3, gain 16, ssid dlink, ntp de.pool.ntp.org
percent = 100 LED = 0
New volume = 0.00
Connect WiFi
DisconnectSoft AP disconnectSet WLAN ModeVerbindung zu dlink herstellen
123asdzxc
.
IP-Adresse = 192.168.0.108
Start
percent = 80 LED = 51
Zeit = 16:20
Start webserver
percent = 80 LED = 51
Show Time
Zeit = 16:21
percent = 80 LED = 51
Show Time
Zeit = 16:22

**Comment by frankyhub** [comment]
Teste mal den LDR:

Test 1
![Bild](https://github.com/frankyhub/Radiowecker/blob/main/pic/LDR-Test1.png)


Test 2
![Bild](https://github.com/frankyhub/Radiowecker/blob/main/pic/LDR-Test2.png)

**Comment by samand587** [comment]
Angeschlossen an Test 2, LDR ist in Ordnung, reagiert auf die Beleuchtung

**Comment by frankyhub** [comment]
Wenn Test 2 funktioniert, kannst du ja die Helligkeit des TFT-Displays direkt über den LDR steuern.

**Comment by samand587** [comment]
Mit dem Test 2 gibt es scharfe Lichtsprünge des Displays. Warum will er nicht so arbeiten, wie es in der Skizze steht? Ich möchte dieses Problem lösen!

**Comment by frankyhub** [comment]
Mit der Version 1.2.4 ist das Problem gelöst.
Änderung:

#define LDR 34
#define TFT_LED  15

//  analogWrite(TFT_LED, ledb); ->   
analogWrite(TFT_LED, ledb)

**Comment by samand587** [comment]
Hallo! Ich habe zu pin 34 gewechselt, der Rest funktioniert wie oben geschrieben - LDR funktioniert nicht.  Als nächstes weiß ich nicht, was ich tun soll?!

**Comment by frankyhub** [comment]
Hallo, TFT_LED auf GPIO15.

**Comment by samand587** [comment]
Ja, ich habe TFT_LED auf GPIO15. Funktioniert aber nicht.

**Comment by frankyhub** [comment]
und die Version 1.2.4 in den ESP laden.

**Comment by samand587** [comment]
" version 1.2.4 in ESP." Was ist hier gemeint?

**Comment by frankyhub** [comment]
Lade das Repo down, kompiliere das Programm und lade dann die Radiowecker.ino in den ESP32. Dann funktioniert der LDR. Du kannst die Änderung der Lichtwerte auch im Seriellen Monitor sehen.

**Comment by samand587** [comment]
Es wird ein Fehler ausgegeben:

C:\Users\User\Documents\Arduino\libraries\ESP32_AnalogWrite-master\src\analogWrite.cpp:47:9: note: suggested alternative: 'ledcAttachPin'

         ledcAttach(pin, _analog_write_channels[i].frequency, _analog_write_channels[i].resolution);

         ^~~~~~~~~~

         ledcAttachPin

**Comment by frankyhub** [comment]
Arduino IDE, Board: ESP32 DEV Module V1.0.6?

**Comment by frankyhub** [comment]
ich habe keinen Fehlermeldung beim kompilieren:
https://github.com/frankyhub/Radiowecker/blob/main/pic/kompile.png
Ich habe meine ESP32_AnalogWrite-master-Library in den Ordner lib kopiert. Versuche es mal mit dieser Library.

**Comment by samand587** [comment]
Es wird ein Fehler ausgegeben:
Arduino: 1.8.19 (Windows 10), Плата:"ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputI2S.cpp: In member function 'bool AudioOutputI2S::SetPinout()':

C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputI2S.cpp:95:41: error: 'i2s_pin_config_t' has no non-static data member named 'mck_io_num'

         .data_in_num = I2S_PIN_NO_CHANGE};
                                         ^
C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputI2S.cpp: In member function 'bool AudioOutputI2S::begin(bool)':

C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputI2S.cpp:232:28: error: 'I2S_MCLK_MULTIPLE_DEFAULT' was not declared in this scope

           .mclk_multiple = I2S_MCLK_MULTIPLE_DEFAULT, // Unused
                            ^
C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputI2S.cpp:233:28: error: 'I2S_BITS_PER_CHAN_DEFAULT' was not declared in this scope

           .bits_per_chan = I2S_BITS_PER_CHAN_DEFAULT // Use bits per sample
                            ^
C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputI2S.cpp:234:7: error: 'i2s_config_t' has no non-static data member named 'mclk_multiple'
       };
       ^
C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputSPDIF.cpp: In constructor 'AudioOutputSPDIF::AudioOutputSPDIF(int, int, int)':

C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputSPDIF.cpp:108:22: error: 'I2S_MCLK_MULTIPLE_DEFAULT' was not declared in this scope

     .mclk_multiple = I2S_MCLK_MULTIPLE_DEFAULT, // Unused                      ^

C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputSPDIF.cpp:109:22: error: 'I2S_BITS_PER_CHAN_DEFAULT' was not declared in this scope

     .bits_per_chan = I2S_BITS_PER_CHAN_DEFAULT // Use bits per sample                      ^

C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputSPDIF.cpp:110:3: error: 'i2s_config_t' has no non-static data member named 'mclk_multiple'

   };
   ^
C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputSPDIF.cpp: In member function 'bool AudioOutputSPDIF::SetPinout(int, int, int)':

C:\Users\User\Documents\Arduino\libraries\ESP8266Audio-1.9.7\src\AudioOutputSPDIF.cpp:159:3: error: 'i2s_pin_config_t' has no non-static data member named 'mck_io_num'

   };
   ^
exit status 1

**Comment by frankyhub** [comment]
ok

**Comment by frankyhub** [comment]
ok
